version: 2

updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "ettu-team"
    assignees:
      - "ettu-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "ettu-team"
    assignees:
      - "ettu-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "ettu-team"
    assignees:
      - "ettu-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "ci/cd"
